### ISSUE TITLE
how to download the correct snli dataset

### ISSUE THREAD

**Issue by hyybuaa** [facebookresearch/InferSent#101]
No such file or directory: 'dataset/SNLI/s1.train'

**Comment by dougc333** [comment]
You have to download the SNLI dataset either use the .bash file provided by the author or do it manually from the website. If you do this manually mkdir and put it in the right place

**Comment by aconneau** [comment]
Hi

```bash
cd dataset
./get_dataset.bash
```

should download automatically the SNLI dataset.
