### ISSUE TITLE
Models are missing on AWS

### ISSUE THREAD

**Issue by universome** [facebookresearch/InferSent#109]
When trying to download models from AWS, via commands from `README.md`
```
curl -Lo encoder/infersent1.pkl https://s3.amazonaws.com/senteval/infersent/infersent1.pkl
curl -Lo encoder/infersent2.pkl https://s3.amazonaws.com/senteval/infersent/infersent2.pkl
```
I obtain the following error:
```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>senteval</BucketName>
<RequestId>1DFCFBB24C8701D5</RequestId>
<HostId>
KpTip/QVjbddWU14lFgr49c1cCAvsdOh82yQqUkeAsBUulXJclRojZj/+9p9mvpI9z906mf4C+c=
</HostId>
</Error>
```

Currently, one can download models, provided (temporarily?) by @habichta [here:](https://github.com/facebookresearch/InferSent/issues/108#issuecomment-459755937)
```
https://drive.google.com/file/d/1pRbvodca415gtrbMJf8EqBf--wOmu9Lf/view?usp=sharing
https://drive.google.com/file/d/1sfIlbc8C5k_CujTF7UrtW_2lvNIH-EhW/view?usp=sharing
```

Please, either update a `README.md` if the models are transferred to Google Drive, or put them back on AWS

**Comment by douwekiela** [comment]
This has now been fixed. We moved to a different S3 URL, see: https://github.com/facebookresearch/SentEval/issues/59. You should be able to use

```
curl -Lo examples/infersent1.pkl https://dl.fbaipublicfiles.com/senteval/infersent/infersent1.pkl
curl -Lo examples/infersent2.pkl https://dl.fbaipublicfiles.com/senteval/infersent/infersent2.pkl
```

**Comment by saippuakauppias** [comment]
infersent2 is the same infersent1!
Please, check issue facebookresearch/InferSent#123
