### ISSUE TITLE
Unable to download InferScent models

### ISSUE THREAD

**Issue by amudha1** [facebookresearch/InferSent#111]
I tried downloading both of the infersent models provided via link:
` curl -Lo encoder/infersent1.pkl https://s3.amazonaws.com/senteval/infersent/infersent1.pkl curl -Lo encoder/infersent2.pkl https://s3.amazonaws.com/senteval/infersent/infersent2.pkl`

Both of them throw same error:
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>senteval</BucketName>

**Comment by theanhle** [comment]
try this one (in the last comment): https://github.com/facebookresearch/InferSent/issues/93
