### ISSUE TITLE
Key Error when using FastText <s>

### ISSUE THREAD

**Issue by NadaOH** [facebookresearch/InferSent#112]
I'm trying to train SNLI model using FastText but I'm getting a Key Error <s> .

In the pretrained fasttext this is not included in the vocabulary, I would like to know how did you treat this token? Did you initilize it with zero?
Also, the <p> and </p> what does it represent in FastText is it used in place of <s> and </s> token or at the word level ?

**Comment by JakobDerPharao** [comment]
How did you fix this problem?
