### ISSUE TITLE
Regarding Fasttext file crawl-300d-2M.vec

### ISSUE THREAD

**Issue by hitzkrieg** [facebookresearch/InferSent#119]
On unzipping the Fasttext file crawl-300d-2M.vec.zip , I came across two files:
crawl-300d-2M-subword.bin  and crawl-300d-2M-subword.vec. However the file crawl-300d-2M.vec expected by demo.ipynb is not there inside this zip leading to error.

**Comment by nreimers** [comment]
I think the URL in the readme is wrong.

Correct URL:
https://dl.fbaipublicfiles.com/fasttext/vectors-english/crawl-300d-2M.vec.zip

**Comment by HenryDashwood** [comment]
Having now tried using InferSent with both files, I'm also pretty sure the url in the README is wrong. For instance, this is the output of the visualize method when I use _crawl-300d-2M.vec_
![image](https://user-images.githubusercontent.com/17177967/56592365-87e79600-65b8-11e9-99f9-47c1725b09b9.png)
However when I use _crawl-300d-2M-subword.vec_ the central bars are more or less inverted with the obviously less important words receiving greater importance.

**Comment by saippuakauppias** [comment]
File in readme is: `crawl-300d-2M-subword.zip`
But need `crawl-300d-2M.vec.zip`

I tested both and `-subword` give me very bad results.
