### ISSUE TITLE
It is not compatible with the new pytorch

### ISSUE THREAD

**Issue by ylmeng** [facebookresearch/InferSent#12]
When I tried to run
`embeddings = model.encode(sentences, bsize=128, tokenize=False, verbose=True)`
I got
`AttributeError: 'LSTM' object has no attribute '_data_ptrs'`

It seems the source code of class 'torch.nn.modules.rnn.LSTM' has changed

**Comment by aconneau** [comment]
Could you print the full error message?

**Comment by aconneau** [comment]
also, what is your pytorch version?

**Comment by ylmeng** [comment]
I did not have any problem with pytorch 0.1.12, but when I used 2.0 I had the error.

Here is the full error message:
`~/InferSent/encoder/models.py in encode(self, sentences, bsize, tokenize, verbose)
    177             if self.use_cuda:
    178                 batch = batch.cuda()
--> 179             batch = self.forward((batch, lengths[stidx:stidx + bsize])).data.cpu().numpy()
    180             embeddings.append(batch)
    181         embeddings = np.vstack(embeddings)

~/InferSent/encoder/models.py in forward(self, sent_tuple)
     44         # Handling padding in Recurrent Networks
     45         sent_packed = nn.utils.rnn.pack_padded_sequence(sent, sent_len)
---> 46         sent_output = self.enc_lstm(sent_packed)[0] #seqlen x batch x 2*nhid
     47         sent_output = nn.utils.rnn.pad_packed_sequence(sent_output)[0]
     48 

/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    222         for hook in self._forward_pre_hooks.values():
    223             hook(self, input)
--> 224         result = self.forward(*input, **kwargs)
    225         for hook in self._forward_hooks.values():
    226             hook_result = hook(self, input, result)

/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py in forward(self, input, hx)
    140                 hx = (hx, hx)
    141 
--> 142         has_flat_weights = list(p.data.data_ptr() for p in self.parameters()) == self._data_ptrs
    143         if has_flat_weights:
    144             first_data = next(self.parameters()).data

/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    260                 return modules[name]
    261         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 262             type(self).__name__, name))
    263 
    264     def __setattr__(self, name, value):

AttributeError: 'LSTM' object has no attribute '_data_ptrs'
`

**Comment by soumith** [comment]
PR pytorch/pytorch#2266 should fix this.
