### ISSUE TITLE
Infersent1 and Inferset2 pretrained models are the same !!

### ISSUE THREAD

**Issue by khalidomari** [facebookresearch/InferSent#123]
curl not working with this links

> curl -Lo encoder/infersent1.pickle https://dl.fbaipublicfiles.com/infersent/infersent1.pkl
> curl -Lo encoder/infersent2.pickle https://dl.fbaipublicfiles.com/infersent/infersent2.pkl

and after trying 

> curl -Lo examples/infersent1.pkl https://dl.fbaipublicfiles.com/senteval/infersent/infersent1.pkl
> curl -Lo examples/infersent2.pkl https://dl.fbaipublicfiles.com/senteval/infersent/infersent2.pkl

The models are downloaded but it seems that they contain the same thing.

> Related to: https://github.com/facebookresearch/InferSent/issues/93

**Comment by saippuakauppias** [comment]
+1

**Comment by yuefei-zhu** [comment]
The access to the files is blocked...

**Comment by MartinPernus** [comment]
Does anyone know whether this file is for GloVe or fastText embeddings?

**Comment by khalidomari** [comment]
> 
> 
> Does anyone know whether this file is for GloVe or fastText embeddings?

It's using Glove Embeddings !

**Comment by aconneau** [comment]
Models are back online now. Thanks for your patience and sorry for the inconvenience.

**Comment by khalidomari** [comment]
> 
> 
> Models are back online now. Thanks for your patience and sorry for the inconvenience.

Thanks

**Comment by sanjita-suresh** [comment]
@aconneau , I am trying to download the new models and there is an error of access denied! what should I do?

**Comment by vishxl** [comment]
> @aconneau , I am trying to download the new models and there is an error of access denied! what should I do?
These are the new locations of the models: 
`!curl -Lo encoder/infersent1.pkl https://dl.fbaipublicfiles.com/infersent/infersent1.pkl`
`!curl -Lo encoder/infersent2.pkl https://dl.fbaipublicfiles.com/infersent/infersent2.pkl`
