### ISSUE TITLE
how to get entailment

### ISSUE THREAD

**Issue by anupamme** [facebookresearch/InferSent#13]
Hello

Perhaps a newbie question. 

Can you tell me how to check entailment between two sentences using Infersent?

**Comment by aconneau** [comment]
InferSent is the name we give to the sentence encoder, not the entailment model.
If you want the classifier in addition to the sentence encoder, you should re-train the full model and save it using train_nli.py.
If you had another entailment task in mind, you can also (as we did for the SICK entailment transfer task) use the InferSent sentence encoder to generate features, freeze them, and only learn a classifier on top.
