### ISSUE TITLE
Which is better? this project vs Universal Sentence Encoder

### ISSUE THREAD

**Issue by guotong1988** [facebookresearch/InferSent#131]
https://www.aclweb.org/anthology/D18-2029

Thank you very much!

**Comment by NancyFulda** [comment]
Depends what you want to use it for. If you're using the embeddings directly to estimate semantic textual similarity, then Universal Sentence Encoder (lite) performs slightly better overall while InferSent does a bit better at distinguishing between a sentence and its negation. InferSent is also way better at representing analogical properties of single-word inputs, so any application that compares the embeddings for sentences to the embeddings for words is likely to do better with InferSent. On the other hand, USE lite does better at detecting important differences in word order.

If you're using the embeddings as pre-trained input features for downstream tasks, I'm afraid I have no insight to offer. I generally use the embeddings directly, and don't have a good feel for their effectiveness at transfer learning.

**Comment by guotong1988** [comment]
Thank you
