### ISSUE TITLE
link for the pre-trained models?

### ISSUE THREAD

**Issue by sanjita-suresh** [facebookresearch/InferSent#133]
I am not able to find the pre-trained models infersent1 and infersent2. Can someone help me?

**Comment by nickyeolk** [comment]
I was able to download them via curl (copied from the readme):
```
curl -Lo encoder/infersent1.pkl https://dl.fbaipublicfiles.com/infersent/infersent1.pkl
curl -Lo encoder/infersent2.pkl https://dl.fbaipublicfiles.com/infersent/infersent2.pkl
```
You can also directly download the model by visiting the link with your browser.

**Comment by sanjita-suresh** [comment]
Thanks a lot @nickyeolk . That works 👍
