### ISSUE TITLE
Determine semantic sentence similarity

### ISSUE THREAD

**Issue by technicatisatio334455** [facebookresearch/InferSent#14]
Hi,
I'm interested in hearing if inferSent is suitable to determine semantic similarity between sentences? By averaging the vectors for the sentence and measuring cosine distance for example.

**Comment by douwekiela** [comment]
Yes, you can just take the cosine of sentence representations. Note that you don't have to average anything, InferSent gives you the sentence representation, which you can use to calculate the similarity (e.g. in unsupervised STS tasks).

**Comment by technicatisatio334455** [comment]
Thank you for the quick answer! Was a bit late and missed that a sentence vector was already provided. 

A short follow up question that i can't find covered anywere: What type of text preprocessing do you recommend? I lower case and turn on tokenisation and this seems to give ok results but would stemming, lemmatisation in any way improve the results?

**Comment by douwekiela** [comment]
You can use the tokenizer from SentEval for text preprocessing if you like (https://github.com/facebookresearch/SentEval/tree/master/data). Stemming and lemmatization may improve results, I don't think we've tried that. It's usually most effective on smaller datasets, but might be worth a try.

**Comment by senjed** [comment]
Hi, I noticed that you guys discussed preprocessing of the text. I want to use inferSent for encoding variable-length paragraphs. In this scenario does it makes more sense to pass the whole paragraph to inferSent (as one sent) or pass sentences and compute the average value of sentence embeddings to get the paragraph embedding? I was wondering if you guys have any observations you can share with me.

**Comment by peacej** [comment]
Are there any examples of fine-tuning / transfer learning using InferSent for sentence/document similarity purposes?
