### ISSUE TITLE
get_data script malfunction

### ISSUE THREAD

**Issue by karlinnolabs** [facebookresearch/InferSent#16]
$ ./get_data.bash 
http://nlp.stanford.edu/data/glove.840B.300d.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   315    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2075M  100 2075M    0     0   383k      0  1:32:18  1:32:18 --:--:--  545k
Archive:  glove.840B.300d.zip
warning [glove.840B.300d.zip]:  76 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [glove.840B.300d.zip]:  reported length of central directory is
  -76 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
  zipfile?).  Compensating...
   skipping: glove.840B.300d.txt     need PK compat. v4.5 (can do v2.1)

note:  didn't find end-of-central-dir signature at end of central dir.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

**Comment by karlinnolabs** [comment]
The glove.840B.300d.zip file cannot be extracted with unzip on mac os, I had to use p7zip instead to get the file extracted, this would mean the get_data script is problematic on mac os. An alternative script might be necessary.

**Comment by aconneau** [comment]
Are you sure the zip file was downloaded correctly before trying to unzip? (https://askubuntu.com/questions/54904/unzip-error-end-of-central-directory-signature-not-found)  I didn't have this issue on my mac.

**Comment by karlinnolabs** [comment]
As sure as I can be for a 2Gb file you didn't include a checksum for.

**Comment by aconneau** [comment]
You can also be 100% sure of it by running those 3 lines of code:
https://github.com/facebookresearch/InferSent/blob/master/dataset/get_data.bash#L17-L19

**Comment by aconneau** [comment]
https://apple.stackexchange.com/questions/208139/how-to-deal-with-unzip-error-on-a-large-file-in-osx . What is your version of unzip? I probably have a different version, explaining why I don't have this issue.
I was guessing unzip was working properly on MacOS ..

**Comment by karlinnolabs** [comment]
UnZip 5.52 of 28 February 2005, by Info-ZIP.  Maintained by C. Spieler.

@aconneau I can't be 100% sure of the files integrity if you don't provide a checksum, in fact in the script I would have embedded the checksum, and would have verified it on download complete, I would also check the output status of unzip to make sure that the file has unzipped properly before deleting it - because the script deletes the archives even on unzip failure I had to download the 2Gb archive again.

**Comment by aconneau** [comment]
Thanks for your suggestions, we welcome PRs.

**Comment by karlinnolabs** [comment]
https://github.com/facebookresearch/InferSent/pull/18

**Comment by karlinnolabs** [comment]
Just signed your contributor agreement if you'd like to pull, I'd suggest testing first as I don't have a linux machine handy here.
