### ISSUE TITLE
get_data tokenizer.sed issue

### ISSUE THREAD

**Issue by karlinnolabs** [facebookresearch/InferSent#17]
Archive:  SNLI/snli_1.0.zip
   creating: SNLI/snli_1.0/
  inflating: SNLI/snli_1.0/.DS_Store  
   creating: SNLI/__MACOSX/
   creating: SNLI/__MACOSX/snli_1.0/
  inflating: SNLI/__MACOSX/snli_1.0/._.DS_Store  
 extracting: SNLI/snli_1.0/Icon      
  inflating: SNLI/__MACOSX/snli_1.0/._Icon  
  inflating: SNLI/snli_1.0/README.txt  
  inflating: SNLI/__MACOSX/snli_1.0/._README.txt  
  inflating: SNLI/snli_1.0/snli_1.0_dev.jsonl  
  inflating: SNLI/snli_1.0/snli_1.0_dev.txt  
  inflating: SNLI/snli_1.0/snli_1.0_test.jsonl  
  inflating: SNLI/snli_1.0/snli_1.0_test.txt  
  inflating: SNLI/snli_1.0/snli_1.0_train.jsonl  
  inflating: SNLI/snli_1.0/snli_1.0_train.txt  
  inflating: SNLI/__MACOSX/._snli_1.0  
**./get_data.bash: ./tokenizer.sed: /bin/sed: bad interpreter: No such file or directory
./get_data.bash: ./tokenizer.sed: /bin/sed: bad interpreter: No such file or directory
./get_data.bash: ./tokenizer.sed: /bin/sed: bad interpreter: No such file or directory
./get_data.bash: ./tokenizer.sed: /bin/sed: bad interpreter: No such file or directory
./get_data.bash: ./tokenizer.sed: /bin/sed: bad interpreter: No such file or directory
./get_data.bash: ./tokenizer.sed: /bin/sed: bad interpreter: No such file or directory**

**Comment by karlinnolabs** [comment]
My sed path is /usr/bin/sed - maybe the script needs a "which sed" rather than a hard coded path?

**Comment by aconneau** [comment]
That's a good point, thanks. I'll make the changes.

**Comment by karlinnolabs** [comment]
I found /usr/bin/env sed -f would be better
