### ISSUE TITLE
Torch causing pain

### ISSUE THREAD

**Issue by karlinnolabs** [facebookresearch/InferSent#19]
RuntimeError: module compiled against API version 0xb but this version of numpy is 0x9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

-- getting this to work on a mac is starting to look impossible

**Comment by aconneau** [comment]
This seems to be linked to a bug in your pytorch installation, not to InferSent.
Did you check this fix:
https://discuss.pytorch.org/t/valueerror-and-importerror-occurred-when-import-torch/5818
?

**Comment by karlinnolabs** [comment]
yep, I had to install it with --user though too because you can't install numpy into the system with macos due to the OS fs protection mechanisms.

**Comment by aconneau** [comment]
fixed: wrong installation of requirements
