### ISSUE TITLE
Problem with ./get_data.bash command

### ISSUE THREAD

**Issue by MargaridanarSousa** [facebookresearch/InferSent#20]
When i run : ./get_data.bash I get the following issue:

/usr/bin/env: ‘sed -f’: No such file or directory

Does anyone know how to solve this problem? 
Thank you very much for the help!

**Comment by aconneau** [comment]
This is due to a recent commit. My bad. I will push a fix in a minute.

**Comment by aconneau** [comment]
Can you try again with this fix? https://github.com/facebookresearch/InferSent/commit/7cab2d2f6f1a7e6dab2cba61aa632589ba578402
