### ISSUE TITLE
Using infersent in long texts

### ISSUE THREAD

**Issue by rsteca** [facebookresearch/InferSent#21]
Hi, if I want to use infersent to represent a long text that is composed of many sentences. What would you recommend? Using the whole text instead of its sentences, I ran out of memory in the GPU. 
Thanks in advance.

**Comment by aconneau** [comment]
Hi I would recommend to take the average of the infersent embeddings of the sentences to represent the text.

**Comment by aconneau** [comment]
This is actually something I may add to InferSent in the near future (document classification using this average).

**Comment by rsteca** [comment]
Mmm, I already tried that, but the resulting vectors were just nonsense. Maybe I did something wrong with my implementation.

**Comment by aconneau** [comment]
Out of curiosity: on what task were you evaluating the aggregated vectors?

**Comment by rsteca** [comment]
It was something wrong with my implementation. The mean of the vectors works well. I was evaluating with text classification.
