### ISSUE TITLE
search of similar sentences

### ISSUE THREAD

**Issue by anupamme** [facebookresearch/InferSent#23]
I have a scenario where I need to solve following issue. It is not really the issue with this repo but more like algorithmic help in using Infersent in a particular case.

So I have a set of n sentences for which I have created encodings using Infersent.

Now I get a query sentence and I want to find similar sentences (among the n sentences) to this sentence.

How do I arrange the n sentences, meaning in what data structure so that I can quickly find top k similar sentences?

Generally, how do I perform search when it comes to sentence encodings.

**Comment by aconneau** [comment]
The problem you mention is that of Fast-KNN for embedding spaces.

If your n is not so large, you can simply compute the k-NN on a GPU (on which it can be relatively fast), i.e you multiply your query (1, 4096) with (4096, n) --> you get n scores that are the inner-product (then you normalize to have the cosine).

Now if you want to go large-scale, or you just want to be super-fast (n being too big for a single GPU), you want to consider our library at Facebook AI Research called "[FAISS](https://github.com/facebookresearch/faiss)", which was specifically designed for efficient similarity search in embedding spaces. It was originally designed for image features, but is perfectly suited for InferSent sentence embeddings. It includes a CPU and a GPU versions that are both super efficient and easy to use.

**Comment by anupamme** [comment]
My n is not so large (< 10000) and I do not have GPU. Would you still recommend using FAISS or I should use the first method you suggested for the GPU but a CPU version of it?

**Comment by 8carlosf** [comment]
The obvious naive way of doing it, would be to compute the distance to each sentence using cosine distance (or any other distance), sort the results a get the top k.
If sorting is slow (it might be fast enough, specially for <10000), you can use the QuickSelect algorithm, which normally only gives you the kth smallest element, but you can modify it to give you the top K.
For example, the kth smallest will always be in the position k of the array, (for x in [1, 2, ..., +inf]) all the k-x will be smaller, and all the k+x will be bigger, you just need to sort the k smallest elements to get them in sorted order.

**Comment by aconneau** [comment]
@8carlosf I think the sorting part here would not be the bottleneck, no matter n.

The matrix multiplication between the query vectors (n_queries, 4096) and the key vectors (4096, n) that gives you the similarity score between keys and values is much more expensive.

@anupamme You can try doing it brute force using numpy matrix multiplications, this may just be enough for n=10K. Otherwise, I would suggest to use CPU-FAISS python package (rather easy to install, and easy to use in python).

**Comment by category-indiamart** [comment]
@aconneau .. i am working on using InferSent with Faiss to do a faster sentence similarity. You mentioned that you wanted to share an eg on how to do so, please share one... it will be great help for me!

**Comment by prachij94** [comment]
@aconneau i also have the same request... @category-indiamart yes,+1 .. i would also appreciate an example for the implementation of InferSent with the FAISS package in python. I also have a GPU with good and compatible configuration for the same, but facing issues at the installation phase itself.

**Comment by nuttwerx** [comment]
@category-indiamart I'm working on this too, we could help each other with it if you'd like cause I'm not really experimented with either project

@prachij94 which issues are you facing? I built and installed faiss for Python-CPU on Debian
