### ISSUE TITLE
Some details on training AllNLI

### ISSUE THREAD

**Issue by windweller** [facebookresearch/InferSent#24]
Hi,

I'm looking at this script `train_nli.py` on the actual training of model. It seems like it only takes in one NLI corpus (SNLI/MultiNLI) at once. So how is the final model tuned? Is it first trained and tuned on SNLI, got the best result, and then (loaded in) trained and tuned for MultiNLI?

**Comment by aconneau** [comment]
Hi,

"AllNLI" (in the paper) is defined as follows:

TRAIN = SNLI TRAIN + MultiNLI TRAIN
DEV = SNLI DEV + MultiNLI MATCHED
TEST = SNLI TEST + MultiNLI MISMATCHED

We just train the model using train_nli.py with the default parameters on this combined dataset.

**Comment by sleepinyourhat** [comment]
Do you have example code to do this? It looks *almost* trivial, when I try combining the datasets outside of Python, I consistently get SentEval results that are worse than what you report (roughly on par with SkipThought).
