### ISSUE TITLE
Unable to reproduce some of the results on transfer tasks

### ISSUE THREAD

**Issue by ottj** [facebookresearch/InferSent#30]
I am unable to reproduce some of the results on transfer tasks. Most results I get are a bit higher than the reported ones. I use the infersent.py script in the SentEval repo.

Setup
p2.xlarge AWS, K80 GPU, deep learning AMI template
CUDA 8
Numpy 1.13.1
scikit-learn 0.19.0
Pytorch 0.2.0.post3

Results vs. reported results:

***** Transfer task : MR *****
Dev acc : 81.8 Test acc : 81.6
Reported: 81.1

***** Transfer task : CR *****
Dev acc : 87.11 Test acc : 86.7
Reported: 86.3

***** Transfer task : SUBJ *****
Dev acc : 92.74 Test acc : 92.33
Reported: 92.4

***** Transfer task : MPQA *****
Dev acc : 90.73 Test acc : 90.63
Reported: 90.2

***** Transfer task : SST Binary
Dev acc : 83.72 Test acc : 85.01
Reported: 84.6

***** Transfer task : TREC *****
Dev acc : 84.3 Test acc : 88.2
Reported:

***** Transfer task : SICK-Relatedness*****
Test : Pearson 0.883687833603 Spearman 0.826056552356 MSE 0.223225237894
Reported:0.884

***** Transfer task : SICK-Entailment****
Dev acc : 86.8 Test acc : 86.26 for
Reported:86.1

***** Transfer task : MRPC *****
Dev acc : 76.15 Test acc 76.52; Test F1 83.17
Reported:

***** Transfer task : STS14 *****
ALL (weighted average) : Pearson = 0.6917,             Spearman = 0.6632
ALL (average) : Pearson = 0.6776,             Spearman = 0.6516
Reported:.68/.65

**Comment by aconneau** [comment]
Hi, thanks for pointing this out. We made a slight improvement in the model, that's probably why you get better results than what's been reported. We will likely make some other improvements to the model soon.
