### ISSUE TITLE
Handling misspellings

### ISSUE THREAD

**Issue by shenkev** [facebookresearch/InferSent#31]
2 quick question,

How well does the encoder of InferSent handle misspellings in text you're trying to encode?
E.g. "A **yello** cat walked down the street"

What do you think will work better to get a single representation of 100 sentences?
1. Taking the average embedding over 100 sentences
2. Concatenating 100 sentences and then embedding the one, long sentence
or will neither work very well?

**Comment by aconneau** [comment]
Hi thanks for your interest in InferSent

The only handling of the misspellings is by using GloVe vectors right now. The > 2M words in the vocabulary of GloVe contain a lot of misspelled words. For instance, "yello" is in the vocabulary of GloVe vectors. Though it can happen that a misspelled word is actually another word: we don't handle that case.


Taking the average of sentence embeddings will definitely work better than the 2nd solution. It should work, other users have tried it too, successfully.

Thanks
