### ISSUE TITLE
STS Benchmark reproducibility

### ISSUE THREAD

**Issue by Tiriar** [facebookresearch/InferSent#32]
Hello,

I am working on a thesis about sentence embeddings and I would like to ask how exactly could I reproduce the reported results of InferSent on the STS Benchmark dataset (75.8 Pearson coef.). I tried to simply download their testing dataset, encode each pair of sentences (lower-casing them) and compute cosine similarity between them, but I only managed to get to a Pearson coef. of 71.0.

I know that you write in the description that I can use the SentEval project to reproduce the results, but it computes loads of other tasks that I am not interested in. I also looked at the code of SentEval and I am a bit confused about how exactly it preprocesses the data and computes the scores. From what I understood it uses the STS dataset from 2014 (I tried that one too, but only got to Pearson coef. of 65.8). I would much rather reproduce the result myself.

So the question is: What is the easies way to reproduce the results on STS benchmark without using the (for me too complicated) SentEval module? Should I preprocess the sentences somehow?

Thanks in advance.

**Comment by aconneau** [comment]
Hi, thanks for your interest in InferSent.

I think it should just be a matter of preprocessing of the STSBenchmark dataset.

Did you preprocess the text? (or use the "tokenize=True" argument?).

You should also lower-case your text.

Thanks

**Comment by aconneau** [comment]
Hi, thanks for your interest in InferSent.

sorry I read your post too fast. The problem is not the preprocessing. For preprocessing STSBenchmark, we just use tokenizer=True and lower-casing.

Though for STSBenchmark, the results we report are not by just using the cosine similarity between sentence embeddings on the test set. It uses the same approach that we use for SICK Relatedness (please refer to our paper for more details on the technique used).

You can reproduce our results using SentEval though. It should be relatively easy to use. We encourage you to try it (try by just making the "bow.py" example work), especially if you write a thesis about sentence embeddings: it would add great value to your thesis to have multiple evaluation.

Thanks

**Comment by Tiriar** [comment]
Thank you, I will have a look ;)

**Comment by Tiriar** [comment]
Hello, I managed to get the infersent.py in SentEval/examples working. I tried two transfer tasks, the STS14 and the STSBenchmark (which uses the SICK relatedness approach), but I still did not get to the Pearson coef. scores reported at http://ixa2.si.ehu.es/stswiki/index.php/STSbenchmark (80.1 on dev set, 75.8 on test set). I got:

```
2017-11-09 13:10:01,115 : deft-forum : pearson = 0.2549, spearman = 0.3180
2017-11-09 13:10:09,103 : deft-news : pearson = 0.6780, spearman = 0.6593
2017-11-09 13:10:16,875 : headlines : pearson = 0.5587, spearman = 0.5132
2017-11-09 13:10:25,435 : images : pearson = 0.7141, spearman = 0.6870
2017-11-09 13:10:33,617 : OnWN : pearson = 0.6418, spearman = 0.6507
2017-11-09 13:10:42,225 : tweet-news : pearson = 0.6615, spearman = 0.6164
2017-11-09 13:10:42,225 : ALL (weighted average) : Pearson = 0.6001, Spearman = 0.5844
2017-11-09 13:10:42,225 : ALL (average) : Pearson = 0.5848, Spearman = 0.5741

{'deft-forum': {'pearson': (0.25488758464932937, 4.1874156582438799e-08), 'spearman': SpearmanrResult(correlation=0.31800588245493799, pvalue=4.9405775195300761e-12), 'nsamples': 450}, 'deft-news': {'pearson': (0.67804613366420219, 9.7399579801952828e-42), 'spearman': SpearmanrResult(correlation=0.65927679925646587, pvalue=8.6955734504625011e-39), 'nsamples': 300}, 'headlines': {'pearson': (0.55874861227725692, 8.4568867814123558e-63), 'spearman': SpearmanrResult(correlation=0.5132152438018206, pvalue=1.2584363185964132e-51), 'nsamples': 750}, 'images': {'pearson': (0.71414861491883963, 5.5093714266668715e-118), 'spearman': SpearmanrResult(correlation=0.68701146562761406, pvalue=7.8888147794732268e-106), 'nsamples': 750}, 'OnWN': {'pearson': (0.64175505816803147, 2.7882046529438394e-88), 'spearman': SpearmanrResult(correlation=0.65066487173863674, pvalue=1.6894237193215251e-91), 'nsamples': 750}, 'tweet-news': {'pearson': (0.66151136091569029, 1.4497656849732558e-95), 'spearman': SpearmanrResult(correlation=0.61637133144017042, pvalue=1.1250763997577674e-79), 'nsamples': 750}, 'all': {'pearson': {'mean': 0.58484956076555827, 'wmean': 0.6000629301070195}, 'spearman': {'mean': 0.57409093238660758, 'wmean': 0.58435543235675824}}}
```

for the STS14 and for the STSBenchmark I got:
```
2017-11-09 13:18:20,043 : Computing embedding for train
2017-11-09 13:19:21,360 : Computed train embeddings
2017-11-09 13:19:21,360 : Computing embedding for dev
2017-11-09 13:19:39,910 : Computed dev embeddings
2017-11-09 13:19:39,910 : Computing embedding for test
2017-11-09 13:19:55,863 : Computed test embeddings
2017-11-09 13:21:11,622 : Dev : Pearson 0.7204637752950752
2017-11-09 13:21:11,622 : Test : Pearson 0.6784272926225665 Spearman 0.6719978368250592 MSE 1.4960822233933295 for SICK Relatedness

{'devpearson': 0.72046377529507521, 'pearson': 0.67842729262256651, 'spearman': 0.6719978368250592, 'mse': 1.4960822233933295, 'yhat': array([ 1.8628243 ,  2.26210429,  2.09919372, ...,  3.97563706, 3.09928336,  3.38805205]), 'ndev': 1500, 'ntest': 1379}
```

This is by simply downloading the STSBenchmark and STS14 datasets, setting the correct paths in infersent.py and executing the script. Is there something else I need to do before to get the correct scores?

Thanks

**Comment by aconneau** [comment]
Note related to this issue: SentEval has been modified recently:

Now the results in the paper on InferSent or Bag-of-words are reproducible in SentEval after the fix for all STS tasks. You will have to download again the transfer tasks data (./get_transfer_data.bash) to get the proper preprocessing on these tasks. Thanks.
