### ISSUE TITLE
The model fails to infer simple temporal relations?

### ISSUE THREAD

**Issue by ylmeng** [facebookresearch/InferSent#34]
I am doing a project on temporal relation retrieval and want to try if I can use the encoder here. However, with a simple experiment, there seems to be some fundamental issue:
I gave four sentences in a list:
`sentences  = ['I went to school after eating breakfast.', 
'I ate breakfast before going to school.', 
'I went to school before eating breakfast.',
'I ate breakfast after going to school.']`

After loading the model and encoding the sentences, I computed the cosine distances (the same function in your demonstration).
cosine(sentences[0], sentences[1]) 0.890059
cosine(sentences[0], sentences[2]) 0.992262
cosine(sentences[0], sentences[3]) 0.899194
cosine(sentences[1], sentences[2]) 0.900831
cosine(sentences[1], sentences[3]) 0.989823
cosine(sentences[2], sentences[3]) 0.898861

Since sentences[0] and sentences[1] have the same meaning (in terms of temporal relations), so do sentences[2] and sentences[3], the scores do not make much sense.
I understand "semantics" can be a vague thing, and sometimes sentences[0] and sentences[2] may be in the same group for certain purposes, but in most everyday use of language, it is not the case.

**Comment by aconneau** [comment]
The cosine similarity between two sentence embeddings are just one part of the information contained in the embeddings.

To evaluate the quality of the cosine similarity, we evaluated on the STS tasks (which evaluates the correlation between the scores obtained with the cosine with the human-labeled ones). Our model is of course not perfect but it obtains a good accuracy on these tasks.

Though note that our encoder was trained with a classifier on top of it. That is, if you want to use the InferSent embeddings for the task you're mentioning (temporal relation retrieval), it would be better to learn a classifier (for example) on this task, on top of the InferSent embeddings.
