### ISSUE TITLE
Dropout usage

### ISSUE THREAD

**Issue by windweller** [facebookresearch/InferSent#38]
I think this probably belongs to a question regarding the paper.

Is dropout found not helpful for InferSent training and subsequent SentEval tasks? Those parameters were set to be 0 as default for `train_nli.py`.

**Comment by wirehack** [comment]
I have the same question. Help would be much appreciated.

**Comment by aconneau** [comment]
@windweller @wirehack : sry for the late answer. That's a good question. Surprisingly, I did not get better results using dropout, so it was set to 0.
