### ISSUE TITLE
Linear projection into label space with bias

### ISSUE THREAD

**Issue by windweller** [facebookresearch/InferSent#42]
Hi,

I noticed in the code https://github.com/facebookresearch/InferSent/blob/master/models.py, the last layer projecting to label space (n_classes). By default, `nn.Linear` will include **bias**. 

Is this a desirable/intentional result? Would bias in here be just capturing the frequency distribution of the labels? I'm wondering if it's a good idea / standard practice to do this....

```python
class ClassificationNet(nn.Module):
    def __init__(self, config):
        super(ClassificationNet, self).__init__()
        # ...
        self.classifier = nn.Sequential(
            nn.Linear(self.inputdim, 512),
            nn.Linear(512, self.n_classes),
        )
```

**Comment by aconneau** [comment]
@windweller this is pretty standard to keep the bias in the fully-connected layers of the classifier.
