### ISSUE TITLE
Error following readme

### ISSUE THREAD

**Issue by abhishekraok** [facebookresearch/InferSent#43]
Hi, when I try to follow the readme and encode sentences I get the following error.

`In [5]: sentences
Out[5]:
['hello how are you?',
 'I will make tea',
 'I will not make tea',
 'He will make tea']

In [7]: embeddings = infersent.encode(sentences)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-87afa088816f> in <module>()
----> 1 embeddings = infersent.encode(sentences)

InferSent/encoder/models.py in encode(self, sentences, bsize, tokenize, verbose)
    211         # unsort
    212         idx_unsort = np.argsort(idx_sort)
--> 213         embeddings = embeddings[idx_unsort]
    214
    215         if verbose:

IndexError: index 1 is out of bounds for axis 0 with size 1
`

**Comment by aconneau** [comment]
Which version of pytorch are you using?

**Comment by aconneau** [comment]
This might be linked to an issue with old versions of pytorch, for which I added a patch here: 4b7f9ec7192fc0eed02bc890a56612efc1fb1147 (you'll need to pull the new version)

**Comment by abhishekraok** [comment]
I used this URL pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp35-cp35m-linux_x86_64.whl.

I see the patch fixes the dimension issue I was running into. I had made a hacky patch  https://github.com/abhishekraok/InferSent/commit/fbfc56c9ec1200436bf341491b0a494ba74cb769 but your patch should hopefully fix the error. Thank you very much for the quick response.
