### ISSUE TITLE
'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by lazyprgmr** [facebookresearch/InferSent#45]
Hi 
np.linalg.norm(model.encode(['the cat eats.'])) gives the error 'NoneType' object has no attribute 'data'.
Kindly help me rectify it.

**Comment by aconneau** [comment]
Were you able to run the ipython notebook example?

**Comment by lazyprgmr** [comment]
No, I was not able to encode sentences. Is/Has the issue being/been fixed?

**Comment by aconneau** [comment]
Could you output the full error message? Thanks

**Comment by aconneau** [comment]
Hi,
we made significant changes to the way InferSent can be loaded so you should be able to load it now hopefully https://github.com/facebookresearch/InferSent/blob/master/encoder/demo.ipynb .
Best,
Alexis

**Comment by aconneau** [comment]
Please re-open if you still have the issue
