### ISSUE TITLE
UnicodeDecodeError while building vocabulary

### ISSUE THREAD

**Issue by nielspetersen** [facebookresearch/InferSent#50]
Helllo, I'm currently encountering an 

`
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 962: character maps to <undefined>
`
while trying to build the vocabulary by using the Glove 840b 300dim word embedings. 

**Environment**
OS = Windows 10
Python = 3.5.4
PyTorch = 0.3.1 (via https://anaconda.org/peterjc123/pytorch)

The full traceback: 

```
Traceback (most recent call last):
...
...
...
  File "<Path>", line 32, in setup
    model.build_vocab_k_words(K=100000)

  File "<Path>", line 142, in build_vocab_k_words
    self.word_vec = self.get_glove_k(K)

  File "<Path>", line 118, in get_glove_k
    for line in f:

  File "<Path>\envs\tensorflow\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 962: character maps to <undefined>
```

I've managed to solve this issue by adding `encoding='utf-8'` in the following block of `encoder/models`:

```python
def get_glove_k(self, K):
        assert hasattr(self, 'glove_path'), 'warning : you need \
                                             to set_glove_path(glove_path)'
        # create word_vec with k first glove vectors
        k = 0
        word_vec = {}
        with open(self.glove_path, encoding='utf-8') as f:
            for line in f:
                word, vec = line.split(' ', 1)
                if k <= K:
                    word_vec[word] = np.fromstring(vec, sep=' ')
                    k += 1
                if k > K:
                    if word in ['<s>', '</s>']:
                        word_vec[word] = np.fromstring(vec, sep=' ')

                if k > K and all([w in word_vec for w in ['<s>', '</s>']]):
                    break
        return word_vec
```
The *.txt file with Glove vectors is encoded in UTF-8 as mentioned at the bottom of https://nlp.stanford.edu/projects/glove/ .

In case you could confirm this issue, I would like to provide a PR.

Best, 
Niels

**Comment by aconneau** [comment]
That's python 2/3 compatibility issues. Best way to handle this is to use "import io" and "io.open(..., encoding='utf-8')". I'll add this soon. 
Many thanks for reporting this.

**Comment by czyzby** [comment]
For anyone checking out this issue because of a similar error, the same exception type can be thrown if you try to load zipped word vectors archive rather the actual file.

**Comment by nishkalavallabhi** [comment]
I had this issue on Windows.  Changing line 109 in models.py to include encoding="utf-8" in the open() call fixed it. I don't think it is a Python 2/3 issue. It is an issue with windows having its default encoding as cp1252  - that was what it pointed to when I got the error (C:\Users\XXX\Python36\lib\encodings\cp1252.py)
