### ISSUE TITLE
AllNLI model compiled for instances without CUDA?

### ISSUE THREAD

**Issue by jattenberg** [facebookresearch/InferSent#6]
I'd like to experiment on my laptop, is it possible to get a non-gpu pickle of the AllNLI model?

**Comment by aconneau** [comment]
Yes it's possible, check out those two lines:
# model = torch.load('infersent.allnli.pickle', map_location=lambda storage, loc: storage)
# model.use_cuda = False

in https://github.com/facebookresearch/InferSent/blob/master/encoder/play.ipynb

**Comment by jattenberg** [comment]
D'OH! should have read a few lines ahead. thanks 👍

**Comment by aconneau** [comment]
So did it work in your case? (just for the record)

**Comment by jattenberg** [comment]
encountering a few unrelated issues getting things working in my MBP, (i can submit a PR once i work through everything)

- [ ] default sed location not set correctly
- [ ] issues unzipping glove vectors

maybe others. i'll just keep pushing through.
