### ISSUE TITLE
Regarding results in the paper

### ISSUE THREAD

**Issue by Viresh-R** [facebookresearch/InferSent#61]
Hey guys,
Does the model which gets 84.5 on SNLI test set use dropout(in the encoder and fc layers)? If so, what's the dropout rate ? 
Also, did you guys experiment with fc layers with more neurons than 512 ? Does it help ?

And thanks so much for sharing the code !

**Comment by aconneau** [comment]
Hi,
dropout didn't help much in our case no. The default setting uses a number of hidden units that was found to work best on validation data.
Best,
Alexis
