### ISSUE TITLE
SSL error when loading fastText models

### ISSUE THREAD

**Issue by o-P-o** [facebookresearch/InferSent#66]
Python 3.6.4, MacOS.

Following the README instructions, I download the fastText vectors and then do

```
mkdir dataset/fastText
curl -Lo dataset/fastText/crawl-300d-2M.vec.zip https://s3-us-west-1.amazonaws.com/fasttext-vectors/crawl-300d-2M.vec.zip
```

This works fine for about 1hr, and then with 36 minutes remaining I get the following error:

```
MacBook-Air-2:InferSentV2 Olly$ curl -Lo dataset/fastText/crawl-300d-2M.vec.zip https://s3-us-west-1.amazonaws.com/fasttext-vectors/crawl-300d-2M.vec.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 66 1453M   66  966M    0     0   224k      0  1:50:21  1:13:22  0:36:59     0
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```

What is happening here and how can I solve the problem? Thanks.

I didn't have this issue a few months ago when using the GloVe vectors in V1.

**Comment by aconneau** [comment]
Hi,
I am not sure what happened there. Did you simply try to download it again?
Thanks
Alexis

**Comment by o-P-o** [comment]
I noticed yesterday that I also had this problem with loading sklearn datasets. 

I think this is an issue for Mac users using Python 3.6 after deprecated Apple-supplied OpenSSL libraries. This worked for me, and has worked for others with a similar problem when loading sklearn datasets:

`$ sudo /Applications/Python\ 3.6/Install\ Certificates.command`

Can read more here: https://github.com/scikit-learn/scikit-learn/issues/10201
