### ISSUE TITLE
Infersent1.pkl is no longer available

### ISSUE THREAD

**Issue by willanxywc** [facebookresearch/InferSent#67]
The download link for Infersent1.pkl is not valid, could you please re-upload one?

**Comment by aconneau** [comment]
Hi,
Could you output the error you got?
Thanks
Alexis

**Comment by aconneau** [comment]
I was able to download it from different servers, so I'm closing this issue. Please re-open if you still have a problem there.

**Comment by Allen8838** [comment]
Hi @aconneau, I ran into the same issue as @willanxywc. I got the following error code from git_bash

![image](https://user-images.githubusercontent.com/35154803/43985950-b69832dc-9cd9-11e8-9baa-0d16f0fed4e4.png)

Would you have any suggestion for how I can resolve this? Thank you.

**Comment by Allen8838** [comment]
Nevermind @aconneau. Just realized that I'm not using the latest InferSent files.
