### ISSUE TITLE
Hard-coded embedding dimension 300

### ISSUE THREAD

**Issue by Tiriar** [facebookresearch/InferSent#70]
Hello,

first of all, thank you for your work, I have used InferSent in my project and it boosted the performance quite a lot without much work :+1: .

I am currently trying to train my own InferSent model with different word embeddings, and I noticed a minor issue with the code. Even though I can change 'params.word_emb_dim' in 'train_nli.py', the parameter is not getting propagated to all functions it uses, where the dimension is hard-coded to 300. In order to use different embeddings, I had to manually change the number on several places throughout the project, making it quite cumbersome.

**Comment by aconneau** [comment]
Hi,

thanks for your message!
hmm yeah that's indeed unfortunate. Could you modify the few lines of code that make this issue and push a PR? That would be great.

Thanks!

**Comment by Tiriar** [comment]
Sure, will do ;)

**Comment by aconneau** [comment]
Merged #73! Thanks!
