### ISSUE TITLE
Add instructions to demo.ipnyb?

### ISSUE THREAD

**Issue by johntiger1** [facebookresearch/InferSent#79]
Just did a clean clone off github and I can't run this file:
https://github.com/facebookresearch/InferSent/blob/master/encoder/demo.ipynb

It complains that "new_models" directory does not exist, but it is not clear to me where this directory comes from. Could you add some more instructions here?  Thanks!

**Comment by aconneau** [comment]
Hi,

sorry this wasn't clear. The MODEL_PATH variable should point to where the infersent1.pkl or infersent2.pkl are located. I just commited to update the default path, which was indeed not in the "new_models" directory. Please let me know what additional instructions you think are needed.
Thank you
Alexis
