### ISSUE TITLE
CPU version?

### ISSUE THREAD

**Issue by anupamme** [facebookresearch/InferSent#8]
Hello,

Is a CPU version of this code available or on the roadmap?

**Comment by aconneau** [comment]
Yes, just load the model this way:
`
model = torch.load('infersent.allnli.pickle', map_location=lambda storage, loc: storage)
model.use_cuda = False
`

as mentioned in https://github.com/facebookresearch/InferSent/blob/master/encoder/play.ipynb .

I will add this information directly to the README.

**Comment by aconneau** [comment]
Added CPU option in README bc165ec3af3cf5df4f46b4906185dc24050ae7ff
