### ISSUE TITLE
How to train InferSent on Urdu dataset

### ISSUE THREAD

**Issue by MFarhatUllah** [facebookresearch/InferSent#80]
hello,
There is any tutorial to train InferSent on any language other then English???  If not then how it is possible?? For Example: If I want train InferSent on Urdu Dataset can I use train_nli.py then how I use it. what chamges are necessory to train it??

**Comment by MFarhatUllah** [comment]
train_nli.py has 'gpu' code implementation. But i have cpu. how to run it on cpu what changes are needed to run it on 'cpu'.. Please help ....

**Comment by aconneau** [comment]
Hi,
for now InferSent can only be trained on English. However we are soon going to release a corpus/method that will include multiple languages, including Urdu. So stay tuned!
About the CPU, unfortunately these LSTM models are too big to be trained on CPU. It would simply be too slow. Once the model is trained however, at inference time, you can generate the embeddings on CPU.
Best
Alexis

**Comment by guotong1988** [comment]
This project do not support training anymore. So do you know a better code for sentence embedding?
Thank you!
