### ISSUE TITLE
InferSent encoder demo with GloVe - Key Error

### ISSUE THREAD

**Issue by Priya22** [facebookresearch/InferSent#81]
I'm trying to run the demo.ipynb notebook in the encoder module, with 300 dimensional GloVe vectors. I've run all the commands as detailed in the Readme and the notebook, but at the `model.encode` command I get an error as follows:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-36-3fb4b1a1a3f7> in <module>()
----> 1 embeddings = model.encode(sentences, bsize=128, tokenize=False, verbose=True)
      2 print('nb sentences encoded : {0}'.format(len(embeddings)))

/ais/hal9000/vkpriya/InferSent-master/encoder/models.py in encode(self, sentences, bsize, tokenize, verbose)
    220         for stidx in range(0, len(sentences), bsize):
    221             batch = Variable(self.get_batch(
--> 222                         sentences[stidx:stidx + bsize]), volatile=True)
    223             if self.is_cuda():
    224                 batch = batch.cuda()

/ais/hal9000/vkpriya/InferSent-master/encoder/models.py in get_batch(self, batch)
    172         for i in range(len(batch)):
    173             for j in range(len(batch[i])):
--> 174                 embed[j, i, :] = self.word_vec[batch[i][j]]
    175 
    176         return torch.FloatTensor(embed)

KeyError: </s>

```
Should I explicitly add the </s> symbol to the word vector file?
Thanks!

**Comment by set92** [comment]
You found some fix? maybe model.build_vocab(sentences, tokenize=True) helps?

**Comment by nlothian** [comment]
I had this error using FastText vectors too.

I did this, but it isn't a great fix:

            for i in range(len(batch)):
                for j in range(len(batch[i])):
                    # this next line here is my change
                    if batch[i][j] != self.eos:
                        embed[j, i, :] = self.word_vec[batch[i][j]]

**Comment by Priya22** [comment]
The error doesn't appear if I use the exact GloVe vectors as specified in the Readme - glove.840B.300d.txt. Probably </s> is missing in the others; maybe increasing the vocab size would help.

**Comment by Priya22** [comment]
@nlothian Ah I see. Thanks!

**Comment by aconneau** [comment]
Hi,
In demo.ipynb, if you use infersent1.pkl please use the standard GloVe vectors (because the LSTM has been trained with these ones) and specify the version in ["params_model"](https://github.com/facebookresearch/InferSent/blob/master/encoder/demo.ipynb). Version is "1" for infersent1.pkl and "2" for infersent2.pkl
Thanks
Alexis
