### ISSUE TITLE
Train new infersent model

### ISSUE THREAD

**Issue by wendysyn89** [facebookresearch/InferSent#82]
Hi,

What should I do or is it possible if I would like to train an infersent model from my own dataset (instead of NLI) or change the vectors file(instead of Glove) for testing?

Your helps are much appreciated.

Thank you.

**Comment by aconneau** [comment]
Hi,
If you want to train a BiLSTM-max on another dataset which for instance includes two input sentences and 5 output classes, you'll have to change the [data loader](https://github.com/facebookresearch/InferSent/blob/master/data.py#L59-L92) here, propagate this change in the other files, and also change the number of classes. Also you can specify your own word embeddings with [this parameter](https://github.com/facebookresearch/InferSent/blob/master/train_nli.py#L29) and [this parameter](https://github.com/facebookresearch/InferSent/blob/master/train_nli.py#L56) in the train_nli.py file. For testing, you'll have to specify the correct word embeddings when setting W2V_PATH in [demo.ipynb](https://github.com/facebookresearch/InferSent/blob/master/encoder/demo.ipynb).

Thank you,
Alexis

**Comment by guotong1988** [comment]
This project do not support training anymore. So do you know a better code for sentence embedding?
Thank you!
