### ISSUE TITLE
Training InferSent on Urdu .txt Dataset

### ISSUE THREAD

**Issue by MFarhatUllah** [facebookresearch/InferSent#85]
I have Urdu data set. But i am facing a problem. How to train InferSent on this data set. Data should be in which format. What type of changes are necessary to train InferSent on urdu dataset. There is possibility that InferSent could no be trained on Urdu data???

**Comment by aconneau** [comment]
Hi,
as specified recently in https://github.com/facebookresearch/InferSent/issues/80, it is not possible for now to train a model on InferSent-Urdu. However we will soon release a dataset that I'm sure you will find useful and which will include Urdu.
Please stay tuned!
Best,
Alexis

**Comment by guotong1988** [comment]
This project do not support training anymore. So do you know a better code for sentence embedding?
Thank you!
