### ISSUE TITLE
 bash get_data.bash failed

### ISSUE THREAD

**Issue by loveJasmine** [facebookresearch/InferSent#9]
mldl@mldlUB1604:~/ub16_prj/InferSent/dataset$ bash get_data.bash 
http://nlp.stanford.edu/data/glove.840B.300d.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   315    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2075M  100 2075M    0     0  1852k      0  0:19:07  0:19:07 --:--:-- 1159k
Archive:  glove.840B.300d.zip
  inflating: GloVe/glove.840B.300d.txt  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.1M  100 90.1M    0     0  2442k      0  0:00:37  0:00:37 --:--:-- 5934k
Archive:  SNLI/snli_1.0.zip
   creating: SNLI/snli_1.0/
  inflating: SNLI/snli_1.0/.DS_Store  
   creating: SNLI/__MACOSX/
   creating: SNLI/__MACOSX/snli_1.0/
  inflating: SNLI/__MACOSX/snli_1.0/._.DS_Store  
 extracting: SNLI/snli_1.0/Icon      
  inflating: SNLI/__MACOSX/snli_1.0/._Icon  
  inflating: SNLI/snli_1.0/README.txt  
  inflating: SNLI/__MACOSX/snli_1.0/._README.txt  
  inflating: SNLI/snli_1.0/snli_1.0_dev.jsonl  
  inflating: SNLI/snli_1.0/snli_1.0_dev.txt  
  inflating: SNLI/snli_1.0/snli_1.0_test.jsonl  
  inflating: SNLI/snli_1.0/snli_1.0_test.txt  
  inflating: SNLI/snli_1.0/snli_1.0_train.jsonl  
  inflating: SNLI/snli_1.0/snli_1.0_train.txt  
  inflating: SNLI/__MACOSX/._snli_1.0  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
unzip:  cannot find or open MultiNLI/multinli_0.9.zip, MultiNLI/multinli_0.9.zip.zip or MultiNLI/multinli_0.9.zip.ZIP.
rm: cannot remove 'MultiNLI/multinli_0.9.zip': No such file or directory
rm: cannot remove 'MultiNLI/__MACOSX': No such file or directory
mv: cannot stat 'MultiNLI/multinli_0.9/multinli_0.9_train.txt': No such file or directory
mv: cannot stat 'MultiNLI/multinli_0.9/multinli_0.9_dev_matched.txt': No such file or directory
mv: cannot stat 'MultiNLI/multinli_0.9/multinli_0.9_dev_mismatched.txt': No such file or directory
rm: cannot remove 'MultiNLI/multinli_0.9': No such file or directory
awk: cannot open MultiNLI/train.multinli.txt (No such file or directory)
rm: cannot remove 'MultiNLI/train.multinli.txt': No such file or directory
awk: cannot open MultiNLI/dev.matched.multinli.txt (No such file or directory)
rm: cannot remove 'MultiNLI/dev.matched.multinli.txt': No such file or directory
awk: cannot open MultiNLI/dev.mismatched.multinli.txt (No such file or directory)
rm: cannot remove 'MultiNLI/dev.mismatched.multinli.txt': No such file or directory
mldl@mldlUB1604:~/ub16_prj/InferSent/dataset$

**Comment by aconneau** [comment]
It seems like the curl command failed in your case.

Can you change "curl -o" to "curl -Lo" there : https://github.com/facebookresearch/InferSent/blob/master/dataset/get_data.bash#L47
and try again? Thanks

**Comment by aconneau** [comment]
370bb1036c0ec2e7a42b0b7dc0f422105a3346f0 added "-L" option in curl.
Let me know if that helped.

**Comment by loveJasmine** [comment]
it works!
