### ISSUE TITLE
model.build_vocab(sentences, tokenize=True) is throwing error

### ISSUE THREAD

**Issue by kartikpandey2** [facebookresearch/InferSent#91]
On executing `model.build_vocab(sentences, tokenize=True)`  error
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 962: character maps to <undefined>` is thrown.
traceback : 
 `model.build_vocab(sentences, tokenize=True)`

 `\models.py", line 139, in build_vocab
    self.word_vec = self.get_w2v(word_dict)`

  `\models.py", line 110, in get_w2v
    for line in f:`

**Comment by vakul-singh** [comment]
can anyone help me out,i am getting the same error!!
