### ISSUE TITLE
Download InferSent models via curl request failing

### ISSUE THREAD

**Issue by AmoghM** [facebookresearch/InferSent#93]
I tried downloading both of the infersent models provided via link:
`
curl -Lo encoder/infersent1.pkl https://s3.amazonaws.com/senteval/infersent/infersent1.pkl
curl -Lo encoder/infersent2.pkl https://s3.amazonaws.com/senteval/infersent/infersent2.pkl`

Both of them throw same error:

> Warning: Failed to create the file encode/infersent/allnli.pickle: No such file or directory

Is there an updated path to download them?

**Comment by pietruh** [comment]
The models are still there, you can check this in your browser by entering https://s3.amazonaws.com/senteval/infersent/infersent1.pkl or https://s3.amazonaws.com/senteval/infersent/infersent2.pkl respectively. You can also download from this source by a web browser.
The root of this cause is that there is no 'encoder' folder in the directory from which you are running curl. You can solve this by:
```
mkdir encoder
curl -Lo encoder/infersent1.pkl https://s3.amazonaws.com/senteval/infersent/infersent1.pkl
curl -Lo encoder/infersent2.pkl https://s3.amazonaws.com/senteval/infersent/infersent2.pkl
```

**Comment by tsiq-peyman** [comment]
Hi

I am witnessing the same problem. 

`curl -Lo encoder/infersent2.pkl https://s3.amazonaws.com/senteval/infersent/infersent2.pkl`

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>senteval</BucketName><RequestId>D37F88F72AE3A33C</RequestId><HostId>
GRJyTXLYwtXSO7Zf+EgBQKcuM9xEBQ/1SiVDWddgcafTjGLd3Sct7xN6WCJhyL6V4boncB8Z62c=</HostId></Error>
```

**Comment by universome** [comment]
@tsiq-peyman I created the issue: https://github.com/facebookresearch/InferSent/issues/109
There are temporary links specified there

**Comment by habichta** [comment]
> @tsiq-peyman I created the issue: #109
> There are temporary links specified there

Just wanted to mention that I am not affiliated with Facebook. The models on google drive are only there temporarily.

**Comment by amudha1** [comment]
So how can one use infersent?

**Comment by douwekiela** [comment]
See the updated documentation: we moved to a different S3 bucket and the the new command to get the models is

```
curl -Lo examples/infersent1.pkl https://dl.fbaipublicfiles.com/senteval/infersent/infersent1.pkl
curl -Lo examples/infersent2.pkl https://dl.fbaipublicfiles.com/senteval/infersent/infersent2.pkl
```

**Comment by rajat315315** [comment]
Still not working!
