### ISSUE TITLE
ValueError: some of the strides of a given numpy array are negative. This is currently not supported,

### ISSUE THREAD

**Issue by thammegowda** [facebookresearch/InferSent#99]
Trying to use pretrained InferSent2 Model ( i.e. fastext) to encode sentences.
The pretrained model works perfectly on CPU (where I have torch=0.4.1)
However, it crashes with cuda backend (where I have torch 1.0.0.dev20181017)

``` python
 File ".../InferSent/models.py", line 224, in encode
    batch = self.forward((batch, lengths[stidx:stidx + bsize])).data.cpu().numpy()
  File ".../InferSent/models.py", line 66, in forward
    sent_packed = nn.utils.rnn.pack_padded_sequence(sent, sent_len_sorted)
  File ".../python3.7/site-packages/torch/nn/utils/rnn.py", line 147, in pack_padded_sequence
    lengths = torch.as_tensor(lengths, dtype=torch.int64)
ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.
```

``` bash
 $ python --version
Python 3.7.0
$ pip list | grep torch
torch           1.0.0.dev20181017
$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
```

**Comment by thammegowda** [comment]
Looks like this is related to https://discuss.pytorch.org/t/torch-from-numpy-not-support-negative-strides/3663

**Comment by mgalbato** [comment]
I also get the exact same error, even on the CPU. I'm using Python 2.7 and Torch 1.0 without CUDA.

**Comment by sashaostr** [comment]
+1 on CPU, Python 3.6,  torch==1.0.0

**Comment by badri-thinker** [comment]
any resolution to stride error?

**Comment by sashaostr** [comment]
wait for this PR to be merged: https://github.com/facebookresearch/InferSent/pull/100
or 
alter models.py manually - add this line  `sent_len_sorted = sent_len_sorted.copy()`
here:
```
       # Sort by length (keep idx)
        sent_len_sorted, idx_sort = np.sort(sent_len)[::-1], np.argsort(-sent_len)	               
        sent_len_sorted = sent_len_sorted.copy()
        idx_unsort = np.argsort(idx_sort)	       
```

**Comment by badri-thinker** [comment]
It worked thanks

**Comment by aconneau** [comment]
Merged PR. Thanks!

**Comment by kaumilturabit** [comment]
This error is still occuring despite being merged. Can anyone help me finding solution to this problem?

**Comment by fooSynaptic** [comment]
@sashaostr thanks, i modified a lot of the source code and it works for me. I believe its the data process issue for i use different dataset.

**Comment by datduong** [comment]
@kaumilturabit, I added copy() like this and it works 

 `idx_sort = np.sort(sent_len)[::-1].copy(), np.argsort(-sent_len)`

**Comment by MahmudRana** [comment]
> wait for this PR to be merged: #100
> or
> alter models.py manually - add this line `sent_len_sorted = sent_len_sorted.copy()`
> here:
> 
> ```
>        # Sort by length (keep idx)
>         sent_len_sorted, idx_sort = np.sort(sent_len)[::-1], np.argsort(-sent_len)	               
>         sent_len_sorted = sent_len_sorted.copy()
>         idx_unsort = np.argsort(idx_sort)	       
> ```

Thanks for the answer and also please change sent_len to sent_len_sorted in the later part of the code. (In case, someone missed that, like me :))

**Comment by amitlohan** [comment]
Convert the numpy array to np.int16 or np.int32 before converting it to tensor.

**Comment by ynuwm** [comment]
This also works for me, thanks very much.
```p
sent_len_sorted, idx_sort = np.sort(sent_len)[::-1], np.argsort(-sent_len)	               
sent_len_sorted = sent_len_sorted.copy()
idx_unsort = np.argsort(idx_sort)
```
